---
name: AntiToolBox
main: NgLamVN\AntiToolBox\Loader
version: 0.1
api: 5.0.0
description: Somehow prevent "some" player using ToolBox client join your server.
author: NgLamVN
website: github.com/NgLamVN
...
